config/routes.rb
BetterHireTdd::Application.routes.draw do

  devise_for :users

  resources :positions do
    resources :questions, except: [:index, :show]
    resources :candidates, only: [:new, :create, :destroy, :index ], controller: "positions/candidates"
  end

  resources :questions, only: [] do 
    resources :answers, except: [:index, :show]
  end
  resources :interviews
  resources :candidates
  get "testing" => 'welcome#test'
  root "welcome#index"

end

app/models/position.rb
class Position < ActiveRecord::Base
  validates :name, presence: true
  has_many :questions
  has_many :candidates
  has_many :interviews
  has_many :candidates, through: :interviews



end

app/controllers/positions/candidates_controller.rb
class Positions::CandidatesController < ApplicationController

  def index
    @position = Position.find(params[:position_id])
    @candidates = Candidate.all_but(@position)
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_filter :authenticate_user!
  before_action :find_position, only: [:edit, :show, :update, :destroy]
  def index
    @positions = Position.all
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new position_params
    if @position.save
      redirect_to @position, notice: "#{@position.name} position has been created!"
    else
      flash.now[:alert]  = "There was an error when creating your job position"
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
    if @position.update_attributes position_params
      redirect_to positions_path, notice: "Your job position has been updated!"
    else
      flash.now[:alert] = "There was an error updating your job position"
      render :edit
    end
  end

  def destroy
    @position.destroy 
    redirect_to positions_path, notice: "Your job position has been deleted."
  end


  private 

  def position_params
    params.require(:position).permit(:name, :description, { candidate_ids: [] })
  end

  def find_position
    @position = Position.find(params[:id])
  end



end

app/views/Positions/_form.html.haml
.container    
  -if @position.errors.present?
    %ul.full-errors
      - @position.errors.full_messages.each do |e|
        %li 
          = e 
  .row
    .form-group.col-xs-12.col-md-6
      = form_for @position do |f|
        = f.label :name
        = f.text_field :name, class: 'form-control'
        %br
        = f.label :description
        = f.text_area :description, class: "form-control"
        %br
        .btn-group
          = f.submit class: "button btn btn-primary"
          .button.btn.btn-default=link_to "Cancel", positions_path
          - if @position.persisted?
            .button.btn.btn-default=link_to "Delete", position_path(@position), method: :delete, data: { confirm: "Are you sure you want to delete this position?" }

app/views/Positions/edit.html.haml
.container
  %h3 Edit:
  = render "form"

app/views/Positions/index.html.haml
.spacer25 
.container
  %h2 Job Position
  .row
    .list-group.col-md-8
      - @positions.each do |position|
        #accordion.panel-group 
          .panel.panel-default.position-panel
            .panel-heading
              .panel-title.with-border
                %a{"data-parent" => "#accordion", "data-toggle" => "collapse", href: "##{dom_id(position)}"}= "#{position.name}"
            .panel-collapse.collapse.out{id:dom_id(position)}
              .info-panel.clear-fix
                %h4
                  .row
                    .col-xs-11
                      = position.description
                .row
                  .col-xs-11.col-xs-offset-1
                .btn-group
                  %button.btn.btn-default.btn-xs= link_to "view questions", position_path(position)
                  %button.btn.btn-default.btn-xs.assign= link_to "Assign a candidate", position_candidates_path(position), remote: true, "data-toggle" => "modal", "data-target" => "#assign_modal"
                  %button.btn.btn-default.btn-xs= link_to "<i class='glyphicon glyphicon-cog'></i> Edit".html_safe, edit_position_path(position)
                .spacer25

  .col-xs-12
    .row
      = link_to "Add a job position", new_position_path, class: "btn btn-primary"

.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id: "assign_modal" }              

 

app/views/Positions/new.html.haml
.container
  %h3 Create a new Job Position
  = render "form"

app/views/Positions/show.html.haml
.container
  .col-sm-12.col-md-8
    %h2
      .row
        .col-xs-7
          = "#{@position.name} template"
        .col-xs-5
          .btn-group.btn-group-xs.pull-right
            %button.btn.btn-default{type:"button"}= link_to "Add a question", new_position_question_path(@position), remote: true, "data-toggle" => "modal", "data-target" => "#new-question"
            %button.btn.btn-default{type:"button"}= link_to "Edit", edit_position_path(@position)
    %p
      = @position.description
    .paper
      %h3 Questions to ask:
      %ul.question-list
        - @position.questions.order("id DESC").each do |question|
          .well
            %li
              = question.title
              .row
                .btn-group
                  %button.btn.btn-default.btn-xs.edit-question{type:"button"}= link_to "Edit", edit_position_question_path(@position, question), remote: true, "data-toggle" => "modal", "data-target" => "##{dom_id(question)}"
                  %button.btn.btn-default.btn-xs.delete-question{type:"button"}= link_to "Delete", position_question_path(@position, question), method: :delete, data: { confirm: "Are you sure you want to delete this template?"}
            .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id:dom_id(question)}
            .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id: "new-question" }              
    %br
    .btn-group
      %button.btn.btn-default{type:"button"}= link_to "Back to all", positions_path

    .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id: "assign_modal" }              