config/routes.rb
BetterHireTdd::Application.routes.draw do

  devise_for :users

  resources :positions do
    resources :questions, except: [:index, :show]
    resources :candidates, only: [:new, :create, :destroy, :index ], controller: "positions/candidates"
  end

  resources :questions, only: [] do 
    resources :answers, except: [:index, :show]
  end
  resources :interviews
  resources :candidates
  get "testing" => 'welcome#test'
  root "welcome#index"

end

app/controllers/interviews/candidates_controller.rb
class Interviews::CandidatesController < ApplicationController

  def index
    @candidates = Candidate.with_template_assigned
  end

  def show
    @candidate = Candidate.find(params[:id])
    @questions_complete = []
    @questions_incomplete = []
    @candidate.position.questions.each do |q|
      if q.answers.where( candidate: @candidate ).count > 0
        @questions_complete << q
      else
        @questions_incomplete << q
      end
    end
  end

def new
  @candidates = Candidate.with_no_template
  @positions = Position.all
end

end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :find_interview, only: [ :show ]

  def index
    @interviews = Interview.all
  end

  def new
    @interview = Interview.new
  end

  def show
    @questions_complete = []
    @questions_incomplete = []
    @interview.position.questions.each do |question|
      if @interview.answers.where( question: question ).present?
        @questions_complete << question
      else
        @questions_incomplete << question
      end
    end
    
  end

  def create  
    @interview = Interview.new interview_params
    if @interview.save
      redirect_to interviews_path, message: "Your interview for #{@interview.candidate.formatted_name} has been created"
    else
      render :new
    end
  end



  private

  def interview_params
    params.require(:interview).permit(:position_id, :candidate_id)
  end

  def find_interview
    @interview = Interview.find(params[:id])
  end
end

app/views/interviews/_answer.html.haml
#accordion.panel-group.question-wrapper
  .panel.panel-default
    .panel-heading
      .row
        .col-xs-9
          %h4.panel-title.with-border
            %a{"data-parent" => "#accordion", "data-toggle" => "collapse", href: "##{dom_id(question)}", class: "#{'collapsed' if defined? collapsed}"}
              = question.title 
        .col-xs-3.stars
          = render 'interviews/stars', question: question
    .panel-collapse.collapse.in{id:dom_id(question), style: "#{'height: 0px;' if defined? collapsed}"}
      .panel-body
        - answer = question.answers.where(interview_id: @interview.id).first || question.answers.new
        = semantic_form_for [question, answer], remote: true,  html: {class: "form-horizontal"} do |f|
          = f.semantic_errors :answer
          = f.input :interview_id, as: :hidden, input_html: {value: @interview.id}
          = f.input :title, as: :text, label: false, input_html: { class: "form-control", rows: 5 }
          .spacer25
          .well.well-sm
            .row
              .col-xs-2.rating-label
                = f.label :rating, "Rating:", class: "radio-inline"
              .col-xs-10 
                = f.input :rating, :as => :radio, label: false, collection: (1..5), :input_html => { class: "rating" }

          %br
          = f.action :submit, button_html: { class: "form-control btn btn-primary", data: { disable_with: "saving..." } }

app/views/interviews/_stars.html.haml
- question.answer_for_interview(@interview).try(:rating).try(:times) do
  %span= icon('star')

app/views/interviews/index.html.haml
.spacer25
.container
  %h2 Interviews
  .row
    .col-sm-12.col-md-8
      - @interviews.each do |interview|
        %ul.list-group
          - if interview.interview_progress != 100
            %li.list-group-item.interview-li
              %h4= interview.candidate.formatted_name
              %hr
              .row
                .col-xs-8
                  %p=link_to "#{interview.position.name}", position_path(interview.position)
                .col-xs-4
                  - if interview.answers.count > 0 
                    = link_to "Continue", interview_path(interview), class: "btn btn-default btn-sm pull-right"
                  - else 
                    = link_to "Start", interview_path(interview), class: "btn btn-default btn-sm pull-right"
              .row
                - if interview.answers.count > 0
                  .col-xs-10
                    .progress.progress-striped
                      .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{interview.interview_progress}", role: "progressbar", style: "width: #{interview.interview_progress}%"}
                  .col-xs-2.percentage
                    %h4= "#{interview.interview_progress}%"
  .spacer25
  - if @interviews.count != 0
    %h2 Completed Interviews
    .row
      .col-sm-12.col-md-8
        - @interviews.each do |interview|
          %ul.list-group
            -if interview.interview_progress == 100
              %li.list-group-item.interview-li
                %h4= interview.candidate.formatted_name
                %hr
                .row
                  .col-xs-8
                    %p= link_to "#{interview.position.name}", position_path(interview.position)
                  .col-xs-4
                    = link_to "Review", interview_path(interview), class: "btn btn-default btn-sm pull-right"





  =link_to "Create a new interview", new_interview_path, class: "btn btn-primary"

app/views/interviews/new.html.haml
.spacer25
.container
  %h3 Create a new interview
  .row
    .col-xs-12.col-sm-6.form-group
      = semantic_form_for @interview do |f|
        = f.input :candidate,required: false, member_label: Proc.new { |t| h(t.first_name + " " + t.last_name) }, input_html: { class: "form-control" }
        = f.input :position, required: false, input_html: { class: "form-control" }
        %br
        = f.action :submit, :as => :button, button_html: { class: "btn btn-primary" }

app/views/interviews/show.html.haml
.spacer50
.container
  %h2= "Interview for #{@interview.candidate.formatted_name}"
  %p
    = "Job Position: #{@interview.position.name}"
    = link_to "edit", edit_position_path(@interview.position)
  -if @interview.interview_progress == 100
    .well.well-sm
      -if @interview.candidate.notes?
        %h4 
          Comments: 
          %span 
            %i.glyphicon.glyphicon-comment
        .well.well-sm
          = @interview.candidate.notes
      -else
        %p= link_to "<i class='glyphicon glyphicon-comment'></i> Add a comment", edit_candidate_path(@interview.candidate)
    .well.well-sm
      %h4
        Overall rating: 
        - @interview.interview_score.try(:floor).try(:times) do
          %span= icon('star')
        - if @interview.interview_score > @interview.interview_score.floor && @interview.interview_score < @interview.interview_score.ceil
          %span= icon("star-half-o") 

  .row
    - if @interview.interview_progress != 100
      .col-xs-12
        %h4 Questions:
        .list-group.incompleted
          - @questions_incomplete.each do |question|
            = render 'answer', question: question
  .row
    .col-xs-12
      %h4 Completed Questions:
      .list-group.completed
        - @questions_complete.each do |question|
          = render "answer", question: question, collapsed: true
  .row
    .col-xs-12
      = link_to "All interviews", interviews_path, class: "btn btn-primary"