config/routes.rb
BetterHireTdd::Application.routes.draw do

  devise_for :users

  resources :positions do
    resources :questions, except: [:index, :show]
    resources :candidates, only: [:new, :create, :destroy, :index ], controller: "positions/candidates"
  end

  resources :questions, only: [] do 
    resources :answers, except: [:index, :show]
  end
  resources :interviews
  resources :candidates
  get "testing" => 'welcome#test'
  root "welcome#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :interview
  validates :title, presence: true
  validates :interview_id, presence: true
  validates :question_id, presence: true
  validates_uniqueness_of :question_id, scope: :interview_id
  

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_question
  before_action :find_interview
  before_action :find_answer, only: [:update, :edit ]

  def create
    respond_to do |format|
      @answer = @question.answers.new answers_params
      @answer.interview = @interview
      if @answer.save
        format.js { render :create }
        format.html { redirect_to interview_path(@interview) }
      else
        format.js { render :new }
        format.html {
                      flash.now[:alert] = "Your answer couldn't be saved."
                      render :new 
                    }
      end
    end
  end

  def new
  end

  def update
    respond_to do |format|
      if @answer.update_attributes answers_params
      format.js { render :update }
      format.html { redirect_to interview_path(@interview), message: "your question has been updated" }
      else
        format.js { render :edit }
        format.html { render :edit }
      end
    end
  end

  private

  def answers_params
    params.require(:answer).permit(:title, :question_id, :interview_id, :rating)
  end

  def find_interview
    @interview = Interview.find(params[:answer][:interview_id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.haml
.container
  -if @answer.errors.present?
    %ul
      - @answer.errors.full_messages.each do |e|
        %li
          = e
  .row
    .form-group.col-xs-5
      = form_for @answer do |f|
        = f.label :Answer
        = f.text_field :body, class: "form-control"
        %br
        = f.submit class: "btn btn-primary"

app/views/answers/create.js.erb
$("#<%= dom_id(@question) %>").parents(".question-wrapper").fadeOut(800, function() {
  $(this).next().slideUp('medium');
  $(this).html("");
  $(".completed").append("<%= j render 'interviews/answer', question: @question %>");
  $("#<%= dom_id(@question) %>").collapse();
});
  

app/views/answers/edit.html.haml
.container
  %h3
    Edit:
  = render "form"
  = link_to "Delete", @answer,  method: :delete , class: "btn btn-default", data: {confirm: "Are you sure?"}

app/views/answers/edit.js.haml
$("##{dom_id(@question)}").collapse();

app/views/answers/new.html.haml
%h3 New Question:

app/views/answers/new.js.haml
$("##{dom_id(@question)} textarea").attr("placeholder", "Answer cannot be blank");

app/views/answers/show.html.haml
.container
  %h2
    = "#{@answer.body} template"

  %p Answers to Ask the Candidate:
  - #@answer.question.each do |answer|

  .well
    %p
      = @answer.body
      = #link_to 'edit answer', edit_answer_path(@answer, question), class: 'btn btn-clear'
      = #link_to 'delete this question', answer_question_path(@answer, question), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-clear"
      = #link_to 'Create Answer', edit_answer_path(answer), class: 'btn btn-primary'
      = #link_to 'Add an answer', new_answer_question_path(@answer), class: 'btn btn-clear'


      =#link_to 'delete this answer', destroy_answer_path(@answer), method: :delete, data: { confirm: 'Are you sure you want to delete the answer?'}, class: "btn btn-clear"
      =#link_to 'Back to all', position_question_path, class: 'btn btn-clear'

app/views/answers/update.js.erb
$("#<%= dom_id(@question) %>").collapse('hide');
var $alert = $("<span class='update-notice'>Updated</span>");
$alert.hide();
$("#<%= dom_id(@question) %>").siblings('.panel-heading').find("h4").append($alert);
$("#<%= dom_id(@question) %>").parent().find(".stars").html("<%= j render 'interviews/stars', question: @question %>")
$alert.fadeIn(1200, function() {
  $(this).fadeOut(1200, function() {
    $(this).remove();
  });
})