config/routes.rb
BetterHireTdd::Application.routes.draw do

  devise_for :users

  resources :positions do
    resources :questions, except: [:index, :show]
    resources :candidates, only: [:new, :create, :destroy, :index ], controller: "positions/candidates"
  end

  resources :questions, only: [] do 
    resources :answers, except: [:index, :show]
  end
  resources :interviews
  resources :candidates
  get "testing" => 'welcome#test'
  root "welcome#index"

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  validates :first_name, :last_name, :email, :phone, :address, presence: :true
  validates :email, uniqueness: :true
  # belongs_to :position
  # has_many :answers
  has_many :interviews, dependent: :destroy
  has_many :positions, through: :interviews
  has_many :answers, through: :interviews

  has_attached_file :avatar, 
                    styles: { large: "800X800>", medium: "300x300>", thumb: "150x150>" }, 
                    default_url: ActionController::Base.helpers.asset_path('missing_avatar.png')

  validates_attachment_size :avatar, less_than: 10.megabytes
  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }


  scope :all_but, lambda { |ids| where("position_id not in (?) OR position_id IS NULL", ids) }
  scope :with_template_assigned, -> { where("position_id IS NOT NULL") }
  scope :with_no_template, -> { where("position_id IS NULL") }

  def formatted_name
    if first_name.nil? || last_name.nil?
    email
    else
      "#{first_name.capitalize} #{last_name.capitalize}".strip
    end
  end

  def interview_progress
    if position.questions.count > 0 && answers.count > 0
      (answers.count.to_f / position.questions.count.to_f) * 100
    else
      0
    end
  end

  def has_position?
    position
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only: [ :show, :edit, :update, :destroy]
  def index
    @candidates = Candidate.all
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new candidate_params
    if @candidate.save
      redirect_to @candidate
    else
      flash.now[:alert]  = "There was a problem creating your candidate"
      render :new
    end  
  end

  def show

  end

  def destroy
    @candidate.destroy
    redirect_to candidates_path, notice: "Your candidate has been deleted."
  end

  def edit
  end

  def update
    if @candidate.update_attributes candidate_params
      redirect_to candidates_path, message: "Your candidate has been updated"
    else
      flash.now[:alert] = "There was a problem updating your candidate"
      render :edit
    end
  end


  private

    def candidate_params
      params.require(:candidate).permit(:first_name, :last_name, :email, :address, :phone, :notes, :position_id, :avatar)
    end

    def find_candidate
      @candidate = Candidate.find(params[:id])
    end
end

app/controllers/interviews/candidates_controller.rb
class Interviews::CandidatesController < ApplicationController

  def index
    @candidates = Candidate.with_template_assigned
  end

  def show
    @candidate = Candidate.find(params[:id])
    @questions_complete = []
    @questions_incomplete = []
    @candidate.position.questions.each do |q|
      if q.answers.where( candidate: @candidate ).count > 0
        @questions_complete << q
      else
        @questions_incomplete << q
      end
    end
  end

def new
  @candidates = Candidate.with_no_template
  @positions = Position.all
end

end

app/controllers/positions/candidates_controller.rb
class Positions::CandidatesController < ApplicationController

  def index
    @position = Position.find(params[:position_id])
    @candidates = Candidate.all_but(@position)
  end
end

app/views/candidates/_form.html.haml
.modal-dialog
  .modal-content
    = semantic_form_for(@candidate) do |f|
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} x
        %h4#myModalLabel.modal-title Candidate
      .modal-body
        = f.semantic_errors :candidate
        = f.input :first_name, required: false, input_html: { class: 'form-control'}
        = f.input :last_name, required: false, input_html: { class: 'form-control'}
        = f.input :avatar, required: false, :label => "Photo", input_html: { class: 'form-control'}
        = f.input :email, as: :email, required: false, input_html: { class: 'form-control'}
        = f.input :address, required: false, input_html: { class: 'form-control', rows: 10, cols: 100}
        = f.input :phone, required: false, input_html: { class: 'form-control'}
        = f.input :notes, input_html: { class: "form-control", rows: 5 }
        %br
      .modal-footer
        .btn-group
          = f.action :submit, as: :button, button_html: { class: "btn btn-primary" }
          - if @candidate.persisted?
            .button.btn.btn-default= link_to "delete", candidate_path(@candidate), method: :delete, data: { confirm: 'Are you sure?' }
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close

app/views/candidates/edit.html.haml
.container
  %h3 Edit your candidate:
  = render "form"

app/views/candidates/edit.js.haml
$("#candidate-edit-modal").html("#{ j render 'candidates/form'}");

app/views/candidates/index.html.haml
.modal.fade{"aria-hidden" => "true", role: "dialog", tabindex: "-1", id: "candidate-edit-modal"}
.modal.fade{"aria-hidden" => "true", role: "dialog", tabindex: "-1", id: "candidate-create-modal"}
.container
  .spacer25 
  %h2 Candidates
  .row
    .list-group.col-md-8.candidate-panel
      - @candidates.each do |candidate|
        #accordion.panel-group 
          .panel.panel-default
            .panel-heading
              .panel-title.with-border
                %a{"data-parent" => "#accordion", "data-toggle" => "collapse", href: "##{dom_id(candidate)}"}
                  = "#{candidate.formatted_name}"
            .panel-collapse.collapse.out{id:dom_id(candidate)}
              .panel-body
                .row
                  .col-xs-12.col-md-4
                    = image_tag candidate.avatar.url(:thumb), class: "image-wrapper"
                  .col-xs-12.col-md-8
                    .info-panel
                      = "<h4><i class='glyphicon glyphicon-envelope'></i> #{candidate.email}</h4>".html_safe 
                    .info-panel
                      = "<h4><i class='glyphicon glyphicon-phone'></i> #{candidate.phone}</h4>".html_safe 
                    .info-panel
                      = "<h4><i class='glyphicon glyphicon-map-marker'></i> #{candidate.address}</h4>".html_safe 
                    .info-panel
                      - if candidate.notes.nil?
                        = link_to "<i class='glyphicon glyphicon-comment'></i> Add a comment".html_safe, edit_candidate_path(candidate) , "data-toggle" => "modal", "data-target" => "#candidate-edit-modal", remote: true
                      - else
                        = "<h4><i class='glyphicon glyphicon-comment'></i> #{candidate.notes}</h4>".html_safe 
                    
                    %p= "Applying for:" unless candidate.positions.empty?
                    - candidate.positions.each do |position|
                      .info-panel
                        = link_to "<h4><i class='glyphicon glyphicon-bookmark'></i> #{position.name}</h4>".html_safe, position_path(position) unless position.nil?
                    .pull-right
                      = link_to "<i class='glyphicon glyphicon-cog'></i>".html_safe, edit_candidate_path(candidate) , "data-toggle" => "modal", "data-target" => "#candidate-edit-modal", class: "btn btn-primary", remote: true
        
  .col-xs-12
    .row
      = link_to "Add a candidate", new_candidate_path, "data-toggle" => "modal", "data-target" => "#candidate-create-modal", class: "btn btn-primary", remote: true, class: "btn btn-primary" 
 

app/views/candidates/new.html.haml
.container
  %h3 Create a candidate:
  = render 'form'

app/views/candidates/new.js.erb
$("#candidate-create-modal").html("<%= j render 'candidates/form' %>");

app/views/candidates/show.html.haml
.container
  .spacer25
  .row
    .col-xs-12.col-sm-6.col-md-6
      .well
        = image_tag @candidate.avatar.url(:thumb), class: "image-wrapper"
        %h3.with-border
          = "#{@candidate.first_name} #{@candidate.last_name}"
        - @candidate.positions.each do |position|
          .info-panel.clear-fix
            = "<h4><i class='glyphicon glyphicon-bookmark'></i> #{position}</h4>".html_safe unless position.nil?
        .info-panel.clear-fix
          = "<h4><i class='glyphicon glyphicon-envelope'></i> #{@candidate.email}</h4>".html_safe 
        .info-panel.clear-fix
          = "<h4><i class='glyphicon glyphicon-phone'></i> #{@candidate.phone}</h4>".html_safe 
        .info-panel.clear-fix
          = "<h4><i class='glyphicon glyphicon-map-marker'></i> #{@candidate.address}</h4>".html_safe 
  %p
    = link_to "edit", edit_candidate_path(@candidate), class: "btn btn-default"
    = link_to "delete", candidate_path(@candidate), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
    = link_to "back to all", candidates_path, class: "btn btn-default"
            